create database student

create table student1(
ID INT,
NAME VARCHAR(20),
AGE INT,
AREA VARCHAR(50)
);


ALTER TABLE STUDENT1 ADD SCORE INT 

INSERT INTO STUDENT1 VALUES (1,'JOHN',15,'TVM',35)
INSERT INTO STUDENT1 VALUES (2,'RAM',15,'EKM',95)
INSERT INTO STUDENT1 VALUES (3,'SAIRA',15,'EKM',65)
INSERT INTO STUDENT1 VALUES (4,'SITA',15,'KLM',77)
INSERT INTO STUDENT1 VALUES (5,'MILAN',15,'THR',46)
INSERT INTO STUDENT1 VALUES (6,'CHRIS',15,'TVM',21)

UPDATE STUDENT1 SET AGE=16 WHERE ID=4
SELECT * FROM STUDENT1


SELECT *,
case 
when score>=90 then 'A'
when score>+60 AND SCORE<90 then 'B'
when score>=30 AND SCORE<60 then 'C'
ELSE 'D'
END AS GRADE
FROM STUDENT1 